### ISSUE TITLE
[feat] 삭제함 바텀 인셋 레이아웃 수정

### ISSUE THREAD

**Issue by anyukyung** [TeamB-um/B-umiOS#125]
## 💡 issue
삭제함 바텀 인셋 레이아웃 수정

## 📝 todo
- [ ] 삭제함 바텀 인셋 레이아웃 수정
- [x] 분리수거함: 당신이 보관한 스트레스입니다 
- [ ] 나의 글 -> 삭제 확인 팝업 presentMode
- [x] 삭제함 -> 설정 팝업 presentMode
