### ISSUE TITLE
[feat] 글쓰기 뷰 CollectionViewCell 기본 선택 기능

### ISSUE THREAD

**Issue by leeinae** [TeamB-um/B-umiOS#14]
## 💡 issue
기본적으로 맨 처음 셀이 선택되어서 나와야함

## 📝 todo
- [x] 첫 태그 선택
- [x] 셀은 전체에서 한 개만 선택
- [x] 송편 현상.. 제거 부탁
- [x] 태그가 없을 때 라벨 추가
- [x] 양 사이드 그라데이션 + 애니메이션
