### ISSUE TITLE
[bug] 보관함 뷰 삭제시 발생하는 버그들

### ISSUE THREAD

**Issue by anyukyung** [TeamB-um/B-umiOS#193]
## 🐞 버그 설명
스크린 샷, 작동 환경 (OS, device 등)을 적어주세요.

## 📝 todo
- [x] 보관함 삭제 지웠는데 화면에 남아있는 오류
- [x] 보관함에 글이 삭제되지 않는 오류
- [x] 보관함에서 글 다중 선택 후 삭제시 앱 충돌 현상 발생
