### ISSUE TITLE
[bug] 카테고리 없을 때 글 작성 충돌

### ISSUE THREAD

**Issue by leeinae** [TeamB-um/B-umiOS#195]
## 🐞 버그 설명
카테고리가 없으면 글 작성 시 앱 크러쉬 현상

## 📝 todo
- [x] 카테고리 outOfIdx 문제? (예상)
- [x] 카테고리 삭제 후 선택 인덱스.. 고쳐
- [x] 노치없는 기기에서 카테고리 안 보이는 이슈 ..
