### ISSUE TITLE
[bug] 디자인 관련 QA 진행

### ISSUE THREAD

**Issue by leeinae** [TeamB-um/B-umiOS#196]
## 📝 todo
- [x] 푸시 후 로티 "미화원의 선물" 라벨 색상 변경
- [x] 글쓰기 후 삭제 (랜덤) 이미지 위치 조정 (노치 없는 기기)
- [x] 글쓰기 뷰 페이지 (접힌 종이) 이미지 비율 조정
- [x] 쓰레기통 이미지 비율 조정 / 안내 라벨 위치도 함께 조정
- [x] 나의 글 뷰 카테고리 태그 송편 현상
- [x] CardCVC 삭제 (안씀)
- [x] 오늘의 선물 팝업 로티 좌우 잘림 현상
- [x] 글쓰기 뷰 페이지 텍스트 필드 비율 이미지에 맞게 조정
- [x] 분리수거함 삭제 팝업 자간 수정
