### ISSUE TITLE
[feat] 네비바 UIComponent 만들기

### ISSUE THREAD

**Issue by leeinae** [TeamB-um/B-umiOS#2]
## 💡 issue
재사용을 위한 네비바 UIView를 만들 예정입니다. 

## 📝 todo
- [ ] UIView로 재사용 가능한 CustomNavigationComponent 만들기
- [ ] 왼쪽 뒤로가기 버튼 (기본값)
- [ ] 오른쪽은 init으로 입력받는 버튼
