### ISSUE TITLE
[feat] 네비게이션 바 통합 작업

### ISSUE THREAD

**Issue by leeinae** [TeamB-um/B-umiOS#205]
## 💡 issue
각 뷰 컨트롤러에서 만들어서 사용했던 네비게이션 바를 통일합니다.
UIVIew 커스텀 클래스를 만들고 재사용 가능하도록 구현할 예정입니다

## 📝 todo
- [x] 네비게이션 바 클래스 생성
- [x] ScreenHeightRatio 변수 만들어서 사용
- [x] 비움 문의 이메일 교체
- [x] 글 삭제 시 네트워크 연결 ...
