### ISSUE TITLE
[feat] 삭제/분리수거함 뷰 레이아웃

### ISSUE THREAD

**Issue by leeinae** [TeamB-um/B-umiOS#25]
## 💡 issue
삭제 / 분리수거 상태 구분해서 뷰를 다르게 짜볼 예정

## 📝 todo
- [x] 팝업 뷰 구현
- [x] 삭제 - 분리수거 상태 분리
- [x] 삭제/분리수거 뷰 레이아웃
- [x] 쓰레기 draggable view 생성
- [x] 드래그 애니메이션 지정
- [x] 버린 후, 메인으로 돌아가기
