### ISSUE TITLE
[feat] 나의 리워드 뷰 레이아웃

### ISSUE THREAD

**Issue by anyukyung** [TeamB-um/B-umiOS#27]
## 💡 issue
나의 리워드 뷰 레이아웃을 짤 것입니다.

## 📝 todo
- [ ] 레이아웃 - 컬렉션뷰로 짤거심
- [ ] 눌렀을 때 리워드 팝업
- [ ] 색깔 여덟개 선배 어케 구분할지, 선배들 코드 훔쳐보면서 맹구현
