### ISSUE TITLE
[feat] 삭제 휴지통, 분리수거함 로딩 적용

### ISSUE THREAD

**Issue by leeinae** [TeamB-um/B-umiOS#42]
## 💡 issue
로딩이라는 명칭이 맞을지는 모르겠는데.. 하여간 적용

## 📝 todo
- [x] 전달받은 배경으로 수정
- [x] 로딩 팝업 뷰 짜고 적용
- [x] 쓰레기 집어넣었을 때 가이드 라벨 사라짐
