### ISSUE TITLE
[feat] 분리수거 관리함 레이아웃, 폰트, 색상 수정 및 기능 구현

### ISSUE THREAD

**Issue by jins0704** [TeamB-um/B-umiOS#53]
## 💡 issue
분리수거 관리함 레이아웃을 다시 잡고 폰트, 색상을 적용하고 기능을 구현할 예정입니다.

## 📝 todo
- [x] 레이아웃 수정
- [x] 폰트, 색상 적용
- [x] 분리수거함 갯수 라벨 기능 구현
- [x] 분리수거함 삭제 기능 구현
